language: java

jdk:
  - openjdk11

branches:
  only:
    - master

jobs:
  include:
    - os: linux
      script:
        - ./runtest.sh
    - os: osx
      script:
        - ./runtest.sh
    - os: windows
      script:
        - ./runtest.bat

notifications:
  email: false
